/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ClarifyCard: typeof import('./src/components/chat/ClarifyCard.vue')['default']
    CompareSelector: typeof import('./src/components/chat/CompareSelector.vue')['default']
    ComplianceNotice: typeof import('./src/components/common/ComplianceNotice.vue')['default']
    ContextUsageBar: typeof import('./src/components/chat/ContextUsageBar.vue')['default']
    CtaSection: typeof import('./src/components/landing/CtaSection.vue')['default']
    DatabaseSection: typeof import('./src/components/landing/DatabaseSection.vue')['default']
    DbSelector: typeof import('./src/components/chat/DbSelector.vue')['default']
    FaqSection: typeof import('./src/components/landing/FaqSection.vue')['default']
    FeatureSection: typeof import('./src/components/landing/FeatureSection.vue')['default']
    FileUploader: typeof import('./src/components/chat/FileUploader.vue')['default']
    FooterSection: typeof import('./src/components/landing/FooterSection.vue')['default']
    GitHubIcon: typeof import('./src/components/common/GitHubIcon.vue')['default']
    HeroSection: typeof import('./src/components/landing/HeroSection.vue')['default']
    HowItWorksSection: typeof import('./src/components/landing/HowItWorksSection.vue')['default']
    LanguageSwitcher: typeof import('./src/components/common/LanguageSwitcher.vue')['default']
    MarkdownRenderer: typeof import('./src/components/common/MarkdownRenderer.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    ReasoningCard: typeof import('./src/components/chat/ReasoningCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowcaseSection: typeof import('./src/components/landing/ShowcaseSection.vue')['default']
    SseStepCard: typeof import('./src/components/chat/SseStepCard.vue')['default']
    SummaryCard: typeof import('./src/components/chat/SummaryCard.vue')['default']
    TrialBanner: typeof import('./src/components/common/TrialBanner.vue')['default']
  }
}
