"""Validate the actual Kombu queues generated by the locked Celery version."""

from __future__ import annotations

from celery.events.receiver import EventReceiver  # type: ignore[import-untyped]

from app.tasks.celery_app import celery_app


def test_pidbox_and_mingle_reply_queue_are_rabbitmq43_compatible() -> None:
    mailbox = celery_app.control.mailbox
    for queue in (mailbox.get_queue("policy-fixture@isolated"), mailbox.get_reply_queue()):
        assert queue.durable is True and queue.exclusive is False
        assert queue.auto_delete is False
        assert queue.expires is not None and queue.expires > 0
        assert queue.message_ttl is not None and queue.message_ttl > 0


def test_gossip_event_queue_uses_durable_queue_with_expiry() -> None:
    with celery_app.connection_for_read("memory://") as connection:
        receiver = EventReceiver(connection, app=celery_app, node_id="policy-fixture")
        queue = receiver.queue
        assert queue.durable is True and queue.exclusive is False
        assert queue.auto_delete is False
        assert queue.expires is not None and queue.expires > 0
        assert queue.message_ttl is not None and queue.message_ttl > 0
