"""Request-scoped reporting rules for model decisions and final reports."""

SQL_EVIDENCE_RULE = (
    "Answer the user's request with the actual verified results and requested output columns. "
    "Keep the report concise. Explain SQL, NULL behavior or types only when requested or "
    "needed to understand a result or failure; do not add a checklist of unrelated semantics. "
    "When explaining projection, use actual SELECT expressions and aliases: a selected "
    "GROUP BY or ORDER BY expression is still projected. Preserve JSON value representation. "
    "Serialization does not establish database type; use the expression, authoritative "
    "metadata and dialect rules. A SUM result does not simply inherit its input precision "
    "and scale declaration. SUM ignores NULL and returns NULL for empty inputs or inputs "
    "that are all NULL. IS NULL is valid, but not the only valid NULL test. "
    "Zero alone cannot prove a CASE/COALESCE branch; evaluate any branch claim against "
    "the actual expression and verified evidence. Counts and predicates establish facts "
    "within their checked scope, not unrelated values or distributions. "
    "databaseName names the database; PostgreSQL databases and schemas are distinct, "
    "while MySQL DATABASE and SCHEMA are synonyms. Acknowledge actual preparation "
    "metadata reads. Distinguish attempted, failed and tool-confirmed successful operations. "
    "Unreported defaults, identity/auto-increment, foreign keys and dependencies remain "
    "unknown; omission proves neither absence nor independence. Omit unsupported claims."
)

COMPARE_REPORT_RULE = SQL_EVIDENCE_RULE + " " + (
    "Deliver a self-contained comparison report from the verified compareDatabases result. "
    "Include observed changes and concrete migration SQL for manual review in this final "
    "answer; if reliable SQL cannot be generated, explain why. Do not claim code or a report "
    "was delivered unless it is present here. Report tool-confirmed actions accurately. "
    "SQL may cover only observed attributes; disclose when missing metadata prevents "
    "complete target equivalence. Dependencies not fully read remain unknown in every "
    "local ordering explanation: do not infer no prerequisites or independent operations. "
    "Label possible renames as hypotheses without replacing observed add/drop changes. "
    "For NUMERIC(p,s), integer capacity is p-s. State version-specific behavior conditionally "
    "unless the version was actually read. On PostgreSQL 9.2+, widening p at unchanged s "
    "avoids heap rewrite, but ALTER TABLE still takes ACCESS EXCLUSIVE locks by default. "
    "Discuss locks and rewrites separately; do not assert outages without evidence. "
    "PostgreSQL DDL can roll back before commit; distinguish already committed effects. "
    "Plain PostgreSQL DROP TABLE uses RESTRICT for external dependencies and may fail; "
    "CASCADE explicitly removes dependents and adds destructive scope, never infer it. "
    "For MySQL 8.0, CREATE/ALTER/DROP generally cause implicit commits; atomic DDL means "
    "statement-level crash safety, not user-transaction rollback. Do not promise a later "
    "failure restores prior DDL. MySQL ALGORITHM values are DEFAULT/INPLACE/COPY/INSTANT; "
    "LOCK values are DEFAULT/NONE/SHARED/EXCLUSIVE. INSTANT is not a LOCK value. "
    "Actual availability, algorithm and locking depend on operation and version; do not "
    "invent observed version or execution behavior. Never execute migration SQL."
)
