"""Shared factuality rules for decision and final-summary model requests."""

SQL_EVIDENCE_RULE = (
    "Separate SQL semantics from observed data facts. Explain the SQL that was actually "
    "executed, including its joins, filters, conditional expressions and aggregates; do not "
    "substitute the semantics of a different expression. Do not claim a column has or "
    "lacks NULL values, or assert its raw type or row count, without verifying that "
    "fact in tool results. A COUNT or SUM result alone does not establish whether "
    "NULL values are present. JSON serialization, the appearance of a returned number, "
    "and a literal used inside an expression do not establish the database expression's "
    "result type. Describe type behavior only when supported by the executed expression, "
    "authoritative metadata and the target database's type rules."
)

COMPARE_REPORT_RULE = SQL_EVIDENCE_RULE + " " + (
    "Write the final answer as a self-contained comparison report using only the "
    "verified compareDatabases result. Include the actual observed differences and "
    "the concrete migration SQL supported by those differences in this final answer "
    "for manual review. If reliable SQL cannot be generated, explain why in the final "
    "answer. If you claim to provide SQL or code, put that SQL or code in this final "
    "answer; do not claim a planned report or code block "
    "was already delivered in earlier reasoning or tool decisions. Describe only "
    "actions confirmed successful by tools as completed. Separate observed metadata "
    "from properties and dependencies that were not completely read. Unreported defaults, "
    "foreign keys, triggers or other dependencies remain unknown; omission is not "
    "evidence of absence. Migration SQL may describe only observed attributes; disclose "
    "when its attribute coverage does not establish complete equivalence to the target. "
    "Report observed changes "
    "as facts; label possible renames as hypotheses without replacing observed add/drop "
    "changes. For NUMERIC(p,s), p is total digits and s is fractional digits, so integer "
    "capacity is p-s. On PostgreSQL 9.2+, widening p at unchanged s avoids a table "
    "rewrite, but ALTER TABLE can still take ACCESS EXCLUSIVE locks (PostgreSQL 16 "
    "default unless noted). Discuss locks and rewrites separately; do not assert an "
    "outage without evidence. PostgreSQL transactional DDL can be rolled back before "
    "commit; distinguish that from effects already committed. On MySQL 8.0, "
    "CREATE, ALTER, and DROP DDL generally cause implicit commits; atomic DDL means "
    "statement-level crash safety, not rollback by the user's transaction. Do not "
    "promise that a later failure restores prior MySQL DDL. Never execute migration SQL."
)
